eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka/
spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
management:
  endpoints:
    web:
      exposure:
        include: '*'
