server:
  port: 10003
auth:
  hello: hello ,this is dev profile
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:h2:mem:h2blog;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: root
    password: root
    driverClassName: org.h2.Driver
